name: Update accessibility data
'on':
  push:
    branches:
      - feature/stats-api
jobs:
  get_data_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: 'npm ci && npm run update-accessibility-data'
      - name: Commit data
        run: |
          git config --global user.name 'Lisa Klein'
          git config --global user.email 'lisaklein@users.noreply.github.com'
          git add .
          git commit -am "Automated data update"
          git push
