name: Automated - Update accessibility data
'on':
  push:
    branches:
      - develop
  schedule:
    - cron: '0 2 * * *'
jobs:
  get_data_and_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
      - name: Create env file
        run: |
          touch .env.secrets
          echo DATA_SA_KEY=${{ secrets.DATA_SA_KEY }} >> .env.secrets
          echo DATA_PROJECT_ID=${{ secrets.DATA_PROJECT_ID }} >> .env.secrets
          echo DATA_STORAGE_BUCKET=${{ secrets.DATA_STORAGE_BUCKET }} >> .env.secrets
          echo DATA_STORAGE_FILE=${{ secrets.DATA_STORAGE_FILE }} >> .env.secrets
      - run: 'npm ci && npm run update-accessibility-data'
      - name: Commit data
        run: |
          git config --global user.name 'Appt Stats'
          git config --global user.email '167291111+stats-appt-org@users.noreply.github.com'
          git add .
          git commit -am "Automated accessibility data update"
          git push
